name: simpleverse
description: A sample command-line verse-generating application.
version: 0.0.1
#homepage: https://www.example.com
author: Filip Hracek <filip.hracek@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  english_words: ^3.1.0
  http: ^0.12.0
